"use client";

import { useState } from "react";
import Link from "next/link";
import { useRouter } from "next/navigation";
import { Save, ArrowLeft, Loader2 } from "lucide-react";
import { useAdmin } from "@/contexts/AdminContext";
import { useCreateProduct } from "@/hooks/useAdminProducts";
import AdminGuard from "@/components/AdminGuard";
import {
  CreateProductRequest,
  ProductImage,
  ProductVariant,
} from "@/types/product.types";
import { useToast } from "@/contexts/ToastContext";
import { fetchCategories } from "@/services/category.service";
import { useQuery } from "@tanstack/react-query";
import VariantManager from "@/components/VariantManager";

// Product interface for form data
interface ProductFormData {
  name: string;
  sku: string;
  category_id: string;
  price: number;
  description: string;
  variation: string;
  images: ProductImage[];
  featured: boolean;
  stock: number;
  variants: ProductVariant[];
}

// Form validation errors
interface FormErrors {
  name?: string;
  category_id?: string;
  price?: string;
  description?: string;
  variation?: string;
  images?: string;
  featured?: string;
  variants?: string;
}

// Initial form state
const initialFormData: ProductFormData = {
  name: "",
  sku: "",
  category_id: "",
  price: 0,
  description: "",
  variation: "",
  images: [],
  featured: false,
  stock: 0,
  variants: [],
};

export default function CreateProductPage() {
  const router = useRouter();
  const { getToken, isAuthenticated } = useAdmin();
  const token = getToken();
  const createProductMutation = useCreateProduct();
  const { success, error } = useToast();

  const [formData, setFormData] = useState<ProductFormData>(initialFormData);
  const [errors, setErrors] = useState<FormErrors>({});
  const [isUploading] = useState(false);

  const { data: categories = [], isLoading: isCategoriesLoading } = useQuery({
    queryKey: ["categories"],
    queryFn: fetchCategories,
  });

  // Handle basic field changes
  const handleFieldChange = (
    field: keyof ProductFormData,
    value: string | number | boolean | ProductVariant[]
  ) => {
    setFormData((prev) => ({
      ...prev,
      [field]: value,
    }));

    // Clear error for this field if it exists in FormErrors
    if (field in errors) {
      setErrors((prev) => ({
        ...prev,
        [field]: undefined,
      }));
    }
  };

  // Handle variant changes
  const handleVariantsChange = (variants: ProductVariant[]) => {
    handleFieldChange("variants", variants);
  };

  // Form validation
  const validateForm = (): boolean => {
    const newErrors: FormErrors = {};

    if (!formData.name.trim()) {
      newErrors.name = "Product name is required";
    }

    if (!formData.category_id) {
      newErrors.category_id = "Category is required";
    }

    if (!formData.description.trim()) {
      newErrors.description = "Description is required";
    }

    // DEPRECATED: Product-level images validation removed
    // Images are now validated at variant level
    // if (formData.images.length === 0) {
    //   newErrors.images = 'At least one product image is required';
    // }

    // Require at least one variant
    if (formData.variants.length === 0) {
      newErrors.variants = "At least one product variant is required";
    } else {
      // Validate that variation type is selected if variants exist
      if (!formData.variation || !formData.variation.trim()) {
        newErrors.variation = "Variation type is required when variants exist";
      }

      // Validate variants if any exist
      const variantSkus = formData.variants.map((v) => v.sku);
      const duplicateSkus = variantSkus.filter(
        (sku, index) => variantSkus.indexOf(sku) !== index
      );

      if (duplicateSkus.length > 0) {
        newErrors.variants = "Variant SKUs must be unique";
      }

      // Check for variants with invalid data
      const invalidVariants = formData.variants.some(
        (variant) =>
          !variant.sku.trim() || variant.price <= 0 || variant.stock < 0
      );

      if (invalidVariants) {
        newErrors.variants =
          "All variants must have valid SKU, price, and non-negative stock";
      }
    }

    setErrors(newErrors);
    return Object.keys(newErrors).length === 0;
  };

  // Handle form submission
  const handleSubmit = async (e: React.FormEvent) => {
    e.preventDefault();

    if (!isAuthenticated || !token) {
      setErrors({ name: "You must be logged in to create products" });
      return;
    }

    if (!validateForm()) {
      return;
    }

    try {
      // Auto-generate SKU for backend compatibility
      const autoGeneratedSku = `FUR-${Date.now()}`;

      const productData: CreateProductRequest = {
        name: formData.name.trim(),
        sku: autoGeneratedSku,
        category_id: formData.category_id,
        price: 0, // Price is set at variant level only
        description: formData.description.trim(),
        variation: formData.variation.trim(),
        images: formData.images,
        featured: formData.featured,
        stock: 0, // Stock is managed at variant level only
        variants: formData.variants,
      };

      await createProductMutation.mutateAsync({
        productData,
        token,
      });

      // Success - show notification and redirect to products list
      success(
        "Product Created Successfully",
        `${formData.name} has been added to your product catalog.`
      );

      router.push("/admin/products");
    } catch (err) {
      console.error("Failed to create product:", err);
      error(
        "Failed to Create Product",
        "There was an error creating the product. Please try again."
      );
    }
  };

  return (
    <AdminGuard>
      <main className="min-h-screen bg-gray-50">
        <div className="max-w-6xl mx-auto px-4 sm:px-6 lg:px-8 py-8">
          {/* Header */}
          <div className="bg-white rounded-lg shadow-sm border border-gray-200 p-6 mb-8">
            <div className="flex items-center justify-between">
              <div className="flex items-center space-x-4">
                <Link
                  href="/admin/products"
                  className="flex items-center text-gray-600 hover:text-gray-900 transition-colors"
                >
                  <ArrowLeft className="h-5 w-5 mr-2" />
                  Back to Products
                </Link>
                <div className="h-6 w-px bg-gray-300" />
                <h1 className="text-2xl font-bold text-gray-900">
                  Create New Product
                </h1>
              </div>
              <div className="flex items-center space-x-3">
                <button
                  type="submit"
                  form="product-form"
                  disabled={createProductMutation.isPending || isUploading}
                  className="flex items-center px-6 py-2 bg-blue-600 text-white rounded-md hover:bg-blue-700 disabled:opacity-50 disabled:cursor-not-allowed transition-colors"
                >
                  {createProductMutation.isPending ? (
                    <Loader2 className="h-4 w-4 mr-2 animate-spin" />
                  ) : (
                    <Save className="h-4 w-4 mr-2" />
                  )}
                  {createProductMutation.isPending
                    ? "Creating..."
                    : "Create Product"}
                </button>
              </div>
            </div>
          </div>

          <form id="product-form" onSubmit={handleSubmit} className="space-y-8">
            {/* Basic Information */}
            <div className="bg-white rounded-lg shadow-sm border border-gray-200 p-6">
              <div className="mb-6">
                <h2 className="text-lg font-semibold text-gray-900">
                  Basic Information
                </h2>
                <p className="text-sm text-gray-600 mt-1">
                  Enter the core product details. SKU, price, and stock are
                  managed at the variant level.
                </p>
              </div>

              <div className="mb-6">
                <label className="block text-sm font-medium text-gray-700 mb-2">
                  Product Name *
                </label>
                <input
                  type="text"
                  value={formData.name}
                  onChange={(e) => handleFieldChange("name", e.target.value)}
                  className={`w-full px-3 py-2 border rounded-md focus:outline-none focus:ring-2 focus:ring-blue-500 focus:border-transparent ${
                    errors.name ? "border-red-300" : "border-gray-300"
                  }`}
                  placeholder="Enter product name"
                />
                {errors.name && (
                  <p className="mt-1 text-sm text-red-600">{errors.name}</p>
                )}
              </div>

              <div className="mb-6">
                <label className="block text-sm font-medium text-gray-700 mb-2">
                  Category *
                </label>
                <select
                  value={formData.category_id}
                  onChange={(e) =>
                    handleFieldChange("category_id", e.target.value)
                  }
                  className={`w-full px-3 py-2 border rounded-md focus:outline-none focus:ring-2 focus:ring-blue-500 focus:border-transparent ${
                    errors.category_id ? "border-red-300" : "border-gray-300"
                  }`}
                  disabled={isCategoriesLoading}
                >
                  <option value="">
                    {isCategoriesLoading
                      ? "Loading categories..."
                      : "Select category"}
                  </option>
                  {categories.map((category) => (
                    <option key={category.id} value={category.id}>
                      {category.name}
                    </option>
                  ))}
                </select>
                {errors.category_id && (
                  <p className="mt-1 text-sm text-red-600">
                    {errors.category_id}
                  </p>
                )}
              </div>

              {/* <div className="mb-6">
              <div className="flex items-center">
                <input
                  type="checkbox"
                  id="featured"
                  checked={formData.featured}
                  onChange={(e) => handleFieldChange("featured", e.target.checked)}
                  className="h-4 w-4 text-blue-600 focus:ring-blue-500 border-gray-300 rounded"
                />
                <label htmlFor="featured" className="ml-2 text-sm text-gray-700">
                  Mark as Featured Product
                </label>
              </div>
            </div> */}

              <div>
                <label className="block text-sm font-medium text-gray-700 mb-2">
                  Description *
                </label>
                <textarea
                  value={formData.description}
                  onChange={(e) =>
                    handleFieldChange("description", e.target.value)
                  }
                  rows={4}
                  className={`w-full px-3 py-2 border rounded-md focus:outline-none focus:ring-2 focus:ring-blue-500 focus:border-transparent ${
                    errors.description ? "border-red-300" : "border-gray-300"
                  }`}
                  placeholder="Enter product description"
                />
                {errors.description && (
                  <p className="mt-1 text-sm text-red-600">
                    {errors.description}
                  </p>
                )}
              </div>
            </div>

            {/* 
            DEPRECATED: Product-level Images (kept for backwards compatibility)
            Images are now managed at the variant level for better product organization.
            Please add images to each product variant in the "Product Variants" section below.
          */}
            {/* Product Images - DEPRECATED */}
            {/* <div className="bg-white rounded-lg shadow-sm border border-gray-200 p-6">
            <h2 className="text-lg font-semibold text-gray-900 mb-6">
              Product Images *
            </h2>
            
            {errors.images && (
              <div className="mb-4 p-3 bg-red-50 border border-red-200 rounded-md">
                <p className="text-sm text-red-600">{errors.images}</p>
              </div>
            )}

            <div className="space-y-4">
              {formData.images.map((image, index) => (
                <div key={index} className="border border-gray-200 rounded-lg p-4">
                  <div className="flex items-start space-x-4">
                    <div className="w-20 h-20 border border-gray-300 rounded-md overflow-hidden bg-gray-50">
                      <Image
                        src={image.url}
                        alt={image.alt || `Product image ${index + 1}`}
                        width={80}
                        height={80}
                        className="w-full h-full object-cover"
                      />
                    </div>
                    <div className="flex-1 space-y-3">
                      <div>
                        <label className="block text-sm font-medium text-gray-700 mb-1">
                          Alt Text
                        </label>
                        <input
                          type="text"
                          value={image.alt || ''}
                          onChange={(e) => {
                            const newImages = [...formData.images];
                            newImages[index] = { ...image, alt: e.target.value };
                            setFormData(prev => ({ ...prev, images: newImages }));
                          }}
                          className="w-full px-3 py-2 border border-gray-300 rounded-md focus:outline-none focus:ring-2 focus:ring-blue-500 focus:border-transparent"
                          placeholder="Describe the image"
                        />
                      </div>
                      <div className="flex items-center space-x-4">
                        <label className="flex items-center">
                          <input
                            type="radio"
                            name="primaryImage"
                            checked={image.is_primary || false}
                            onChange={() => setPrimaryImage(index)}
                            className="h-4 w-4 text-blue-600 focus:ring-blue-500 border-gray-300"
                          />
                          <span className="ml-2 text-sm text-gray-700">Primary Image</span>
                        </label>
                      </div>
                    </div>
                    <button
                      type="button"
                      onClick={() => removeImage(index)}
                      className="p-2 text-red-600 hover:bg-red-50 rounded-md transition-colors"
                    >
                      <X className="h-4 w-4" />
                    </button>
                  </div>
                </div>
              ))}

              <label
                htmlFor="image-upload"
                className={`block border-2 border-dashed border-gray-300 rounded-lg p-6 cursor-pointer hover:border-blue-400 hover:bg-blue-50 transition-colors ${
                  isUploading ? 'pointer-events-none opacity-50' : ''
                }`}
              >
                <div className="text-center">
                  <Upload className="mx-auto h-12 w-12 text-gray-400" />
                  <div className="mt-4">
                    <span className="mt-2 block text-sm font-medium text-gray-900">
                      Upload product image
                    </span>
                    <span className="mt-1 block text-sm text-gray-500">
                      PNG, JPG, WebP up to 10MB
                    </span>
                  </div>
                  {isUploading && (
                    <div className="mt-4 flex items-center justify-center">
                      <Loader2 className="h-5 w-5 animate-spin text-blue-600 mr-2" />
                      <span className="text-sm text-gray-600">Uploading...</span>
                    </div>
                  )}
                </div>
                <input
                  id="image-upload"
                  type="file"
                  accept="image/*"
                  onChange={(e) => {
                    const file = e.target.files?.[0];
                    if (file) {
                      handleImageUpload(file);
                    }
                  }}
                  className="sr-only"
                  disabled={isUploading}
                />
              </label>
            </div>
          </div> */}

            {/* Notice about image upload location */}
            <div className="bg-blue-50 border border-blue-200 rounded-lg p-6">
              <div className="flex items-start">
                <div className="flex-shrink-0">
                  <svg
                    className="h-5 w-5 text-blue-600"
                    fill="currentColor"
                    viewBox="0 0 20 20"
                  >
                    <path
                      fillRule="evenodd"
                      d="M18 10a8 8 0 11-16 0 8 8 0 0116 0zm-7-4a1 1 0 11-2 0 1 1 0 012 0zM9 9a1 1 0 000 2v3a1 1 0 001 1h1a1 1 0 100-2v-3a1 1 0 00-1-1H9z"
                      clipRule="evenodd"
                    />
                  </svg>
                </div>
                <div className="ml-3">
                  <h3 className="text-sm font-medium text-blue-800">
                    Product Images
                  </h3>
                  <p className="mt-1 text-sm text-blue-700">
                    Product images are now managed at the variant level. Please
                    add images to each variant in the{" "}
                    <strong>Product Variants</strong> section below. This allows
                    each variant (size, color, material) to have its own
                    specific images.
                  </p>
                </div>
              </div>
            </div>

            {/* Product Variants */}
            <div className="bg-white rounded-lg shadow-sm border border-gray-200 p-6">
              <VariantManager
                variants={formData.variants}
                onVariantsChange={handleVariantsChange}
                selectedVariation={formData.variation}
                onVariationChange={(variation) =>
                  handleFieldChange("variation", variation)
                }
                isEditing={true}
                errors={{
                  ...(errors.variants ? { variants: errors.variants } : {}),
                  ...(errors.variation ? { variation: errors.variation } : {}),
                }}
              />
            </div>
          </form>
        </div>
      </main>
    </AdminGuard>
  );
}
